Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Shel.Neos.Terminal:Terminal:
            resource: resource://Shel.Neos.Terminal/Public/Assets/Plugin.js
        stylesheets:
          Shel.Neos.Terminal:Terminal:
            resource: resource://Shel.Neos.Terminal/Public/Assets/Plugin.css

      frontendConfiguration:
        'Shel.Neos.Terminal:Terminal':
          enabled: false
          welcomeMessage: 'Shel.Neos.Terminal:Main:welcome'
          registrationKey:
            id: ''
            signature: ''
            showThankYouMessage: true
          getCommandsEndPoint: '/neos/shel-neos-terminal/getcommands'
          checkCommandsEndPoint: '/neos/shel-neos-terminal/checkcommands'
          invokeCommandEndPoint: '/neos/shel-neos-terminal/invokecommand'
          theme:
            contentStyle:
              color: '#adadad'
            styleEchoBack: 'fullInherit'
            promptLabelStyle:
              color: '#ff8700'
              whitespace: 'nowrap'
            inputTextStyle:
              color: '#ffffff'
            messageStyle:
              whiteSpace: 'pre-wrap'
              color: '#00adee'

        hotkeys:
          'Shel.Neos.Terminal.toggle': 't t'

    userInterface:
      translation:
        autoInclude:
          Shel.Neos.Terminal: ['Main']

